### ISSUE TITLE
Undefined Index error upsets json

### ISSUE THREAD

**Issue by Jbithell** [BluePost/BlueAjax#6]
``` php
$response = new BluePost\AjaxResponse();
//Check if the GET index "q" isset, if not, die with an error: '{"error":"q not set"}'
$response->assert(GETisset("q"), error("q not set"));
```

Returns:
![12769423_1661828664034720_8054312_n](https://cloud.githubusercontent.com/assets/8408967/13374498/1450399c-dd7e-11e5-9a3a-e0ad42b15102.jpg)

This is now invalid Json :-1:

**Comment by vogon101** [comment]
This is now fixed
